apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dja1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-dja1@sha256:70036634e5615f9e058bc5d84c49f13bb1636a63a6ea1454c4badec7e0a112a4
        name: my-nodejs
        resources: {}
status: {}
