apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dja1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dja1
    app.kubernetes.io/part-of: tkrw-pr712-0075-0049-app
  name: devfile-sample-dja1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dja1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dja1
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-dja1@sha256:70036634e5615f9e058bc5d84c49f13bb1636a63a6ea1454c4badec7e0a112a4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
